---
- name: Dev
  hosts:  "{{hosts}}"
  become: true
  vars:
    default_container_name: weighttracker
    default_container_image: eduardgu/weighttracker:"${phase}"
    default_container_command: sleep 1d

  tasks:

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Check if docker exists
    package:
      name: docker-ce
      state: present
    check_mode: true
    register: docker_check

  - name: Get Docekr GPG
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    when: not docker_check.changed 

  - debug:
      msg: docker_check

  - name: Instal Docker dependencies
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl 
        - gnupg 
        - lsb-release 
      state: latest
      update_cache: true
    when: not docker_check.changed 

  - name: Set Repository
    shell:   echo \
                "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    when: not docker_check.changed 

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Install Docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io 
      state: latest
      update_cache: true
    when: not docker_check.changed 

  - name: Pull Image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull

  - name: Run Container
    docker_container:
      name: "{{ default_container_name }}"
      image: "{{ default_container_image }}"
      ports:
      - "8080:8080"  
      recreate: yes
      force_kill: yes