---
- name: Dev
  hosts: dev #${hosts}
  become: yes
  
  tasks:

  - name: Install "Git"
    apt:
      name: git
      state: latest

  - name: Update "NodeJS" deb
    shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

  - name: Install "NodeJS"
    apt:
      name: nodejs
      state: latest

  - name: Install "pm2"
    shell: npm install pm2 -g

  - name: Create a directory if it does not exist
    file: 
      path: "~/weighttrackertst"
      state: directory
      mode: '0755'

  - name: Download "App" from git
    git: 
      repo: git@github.com:Eduardgur/WeightTrackerTst.git
      version: main
      dest: ~/weighttrackertst/
      accept_hostkey: yes
      key_file: ~/.ssh/id_rsa

  - name: Install node packages
    shell: npm install
    args:
      chdir: "~/WeightTrackerTst/"

  # - name: Initialize DB
  #   shell: npm run initdb
  #   args:
  #     chdir: "/home/eduardgu/WeightTrackerTst"
      
  # - name: clear process
  #   shell: pm2 delete all
  #   ignore_errors: yes

  # - name: run application
  #   shell: pm2 start npm -- run dev && pm2 save && pm2 startup
  #   args:
  #     chdir: "/home/eduardgu/WeightTrackerTst"

   